version: "3"

services:
  phoenix_api_toolkit_1.12:
    image: elixir:1.12-alpine
    working_dir: /application
    # The top mount mounts the local source code into the container for compilation and running.
    # The other mounts effectively function as exclusions on the top mount, to prevent build artifacts from being created locally (as root).
    # Some of the other mounts are mapped to docker volumes to improve build-on-build performance by caching the build artifacts.
    # To completely clean the volumes, execute `docker-compose down -v` in a shell. A subsequent `docker-compose up` will run in a fresh environment.
    volumes:
      - .:/application:cached
      - /application/.elixir_ls
      - /application/cover
      - 1.12__build:/application/_build
      - 1.12_deps:/application/deps
      - 1.12_mix:/root/.mix
    environment:
      MIX_ENV: dev
    command: /bin/sh /application/docker/cmd.sh

  phoenix_api_toolkit_1.10:
    image: elixir:1.10-alpine
    working_dir: /application
    volumes:
      - .:/application:cached
      - /application/.elixir_ls
      - /application/cover
      - 1.10__build:/application/_build
      - 1.10_deps:/application/deps
      - 1.10_mix:/root/.mix
    environment:
      MIX_ENV: dev
    command: /bin/sh /application/docker/cmd.sh

  phoenix_api_toolkit_1.7:
    image: elixir:1.7-alpine
    working_dir: /application
    volumes:
      - .:/application:cached
      - /application/.elixir_ls
      - /application/cover
      - 1.7__build:/application/_build
      - 1.7_deps:/application/deps
      - 1.7_mix:/root/.mix
    environment:
      MIX_ENV: dev
    command: /bin/sh /application/docker/cmd.sh

volumes:
  1.12__build:
  1.12_deps:
  1.12_mix:
  1.10__build:
  1.10_deps:
  1.10_mix:
  1.7__build:
  1.7_deps:
  1.7_mix:
