name: CD / Publish release
on:
  release:
    types: [published]

jobs:
  deploy:
    if: (github.actor == 'TimPelgrim' || github.actor == 'juulSme')
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Display build environment
        run: printenv
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version
        uses: weareyipyip/set-version-action@v2
        with:
          source: tag
          file_path: mix.exs
      - name: Set version
        uses: weareyipyip/set-version-action@v2
        with:
          source: tag
          file_path: README.md
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.x
          elixir-version: 1.10.x
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs
      - name: Publish release
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
