name: CI / Automated testing
on:
  push:
    # run every branch except master
    branches:
      - "**"
      - "!master"
  # allow manual build triggering
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        elixir: [1.7.x, 1.8.x, 1.9.x, 1.10.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.x
          elixir-version: ${{matrix.elixir}}
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build

          key: cache-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            cache-${{ matrix.elixir }}-
      - name: Display build environment
        run: printenv
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests (with coverage)
        run: mix test --cover
      - name: Create docs
        run: mix docs